Algoritmo "exercicio_k_slide7"

Var
A: inteiro

Inicio
Escreval ("                Leitura de um número inteiro")
Escreval ("            para apresentar se está entre 1 e 9.")
Escreval ()
Escreval ()


Escreval ("Digite um número: ")
Leia (A)

Se (A >= 1) e (A <=9) entao
Escreval ("O valor está na faixa permitida")

Senao

Escreval ("O valor está fora da faixa permitida")

Fimse


Fimalgoritmo



fimalgoritmo
