algoritmo "exercicio_i_slide2"

var
numero: inteiro


inicio
Escreval ()
Escreval ("                            ------------------------")
Escreval ("                             Calcular o quadrado de")
Escreval ("                                 de um número")
Escreval ("                            ------------------------")
Escreval ()

Escreval ("Digite um número inteiro: ")
Leia (numero)

Escreval (numero," N ^ 2",numero^2)


fimalgoritmo
