algoritmo "exercicio_o_slide8"

var
A, Multiplicacao: inteiro

inicio
Escreval()
Escreval("                      Apresentar o resultado da multiplicação")
Escreval("                      apenas para um número inteiro maior 30")
Escreval()
Escreval()

Escreval ("Digite um número: ")
Leia (A)

Multiplicacao <- A*2

Se Multiplicacao >= 30 entao
   Escreval ("O resultado é: ",Multiplicacao)

Senao

Fimse

fimalgoritmo
