algoritmo "exercicio_j_slide7"

Var
A: inteiro

Inicio

Escreval()
Escreval("                        Leitura de um numero inteiro ")
Escreval("                      para demonstrar se é impar ou par")
Escreval()
Escreval()

Escreval ("Digite um número: ")
Leia (A)

Se (A mod 2 = 0) entao

Escreval ("O número ",A," é PAR!")

Senao

Escreval ()
Escreval ("O número ",A," é IMPAR!")


Fimse


fimalgoritmo
