algoritmo "exercicio_a_slide1"

var
C, F: real

inicio
Escreval ()
Escreval ("                      -------------------------------------")
Escreval ("                   Conversão em graus Celcius para Fahrenheit")
Escreval ("                      -------------------------------------")
Escreval ()

Escreval ("Digite a temperatura em Celcius para a conversão: ")
Leia (C)

F <- C*9/5+32

Escreval ()
Escreval ("O valor de Celsius para Fahrenheit é: ",F)


fimalgoritmo
